version: '3.1'
services:
  s_jenkins:
    container_name: c_jenkins
    image: turgaydede/jenkinswithdocker
    ports:
      - 8080:8080
    volumes:
      - /opt/app_data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
